---
- name: Check if Docker is installed
  command: which docker
  register: docker_check
  ignore_errors: yes
  changed_when: false

- name: Install required packages
  block:
    - name: Install required packages on Debian/Ubuntu
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      become: yes

    - name: Notify user to install Docker on macOS
      debug:
        msg: "Docker needs to be installed via Docker Desktop on macOS. Please download and install from https://www.docker.com/products/docker-desktop"
      when: ansible_os_family == "Darwin" and docker_check.rc != 0

- name: Start Docker service (Linux)
  systemd:
    name: docker
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"
  become: yes

- name: Verify Docker is running
  command: docker info
  register: docker_info
  changed_when: false
  ignore_errors: yes

- name: Run Jenkins container
  docker_container:
    name: jenkins-app
    image: jenkins/jenkins:lts
    state: started
    restart_policy: always
    published_ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
  when: docker_info.rc == 0