- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Install Docker dependencies
  apt:
    name: docker.io
  state: present
    update_cache: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Log into Docker Hub
  docker_login:
    username: "{{ lookup('env', 'DOCKER_HUB_CREDS_USR') }}"
    password: "{{ lookup('env', 'DOCKER_HUB_CREDS_PSW') }}"
    state: present

- name: Pull latest Docker image
  docker_image:
    name: "{{ docker_image }}:{{ docker_tag }}"
    source: pull
    force_source: yes

- name: Stop and remove existing container if it exists
  docker_container:
    name: "{{ container_name }}"
    state: absent
    force_kill: yes
  ignore_errors: yes

- name: Run Docker container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image }}:{{ docker_tag }}"
    state: started
    restart_policy: always
    ports:
      - "{{ host_port }}:{{ container_port }}"
