apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: selinamjo1/jenkins:latest
        ports:
        - containerPort: 8080
        env:
        - name: JENKINS_OPTS
          value: "--httpPort=8080"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          tcpSocket:
            port: 8080
            host: localhost
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
            host: localhost
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 5 
          failureThreshold: 3
