- name: Deploy ABC Retail App Container
  hosts: docker_hosts
  become: yes
  vars:
    docker_image: selinamjo1/jenkins
    docker_tag: latest
    container_name: jenkins
    container_port: 8080
    host_port: 80

  roles:
    - docker-deploy
